### ISSUE TITLE
Passing index parameter making storage problems

### ISSUE THREAD

**Issue by JacopKane** [UnionOfRAD/li3_docs#13]
I'm including docs library like this:

Libraries::add('li3_docs', array('url' => '/docs', 'index' => $libraryList));

And it throws:

```
Notice: Undefined index: category in /Volumes/NODstorage/Sites/libraries/lithium-docs/resources/tmp/cache/templates/template_views_api_browser_index.html_24994808_1337791326_1204.php on line 6
```

Not happening when adding them all with Libraries::add().

**Comment by davidpersson** [comment]
This logic has been rewritten and the error you saw should be fixed now.
